global:
  scrape_interval: 30s
  scrape_timeout: 10s
  evaluation_interval: 5s
scrape_configs:
  - job_name: prometheus
    scheme: http
    static_configs:
      - targets:
        - prometheus:9090
  - job_name: grafana
    scheme: http
    static_configs:
      - targets:
        - grafana:3000
  - job_name: traefik
    scheme: http
    static_configs:
      - targets:
        - traefik:8080
